Accepts image url
vtex-apps/tab-layout pull request #10
Opened 2020-03-25 00:01 UTC by lucasayb

#### What problem is this solving?
Adds an image in the tab item

#### How should this be manually tested?
Just linking and adding the attribute `imrUrl` to the `tab-list.item`

#### Checklist/Reminders

- [ x] Updated `README.md`.
- [x ] Updated `CHANGELOG.md`.
- [ ] Linked this PR to a Clubhouse story (if applicable).
- [ ] Updated/created tests (important for bug fixes).
- [ ] Deleted the workspace after merging this PR (if applicable).

#### Screenshots or example usage
<img width="1330" alt="Screen Shot 2020-03-24 at 20 46 27" src="https://user-images.githubusercontent.com/17356081/77487909-7800b380-6e12-11ea-8bbe-7ab80cee3f0c.png">

#### Type of changes

✔️ | Type of Change
---|---
_ | Bug fix 
✔️| New feature 
_ | Breaking change 
_ | Technical improvements

2020-03-25 00:02 UTC, regis-samurai submitted a review, later dismissed

2020-03-25 17:29 UTC, klzns commented
I created a new block called `tab-list.item.children` which makes it possible for the following:

```json
"tab-list": {
    "children": [
      "tab-list.item.children#1",
      "tab-list.item.children#2"
    ]
  },

  "tab-list.item.children#1": {
    "props": { "tabId": "home1" },
    "children": [
      "rich-text#1"
    ]
  },
```

2020-03-25 17:36 UTC, kaisermann submitted a review, later dismissed

2020-03-25 17:38 UTC, lbebber submitted a review, later dismissed

2020-03-25 18:29 UTC, iaronaraujo requested changes

2020-03-25 18:29 UTC, iaronaraujo commented on yarn.lock
> +
Remove this please

2020-03-25 19:27 UTC, iaronaraujo approved these changes

2020-03-25 19:30 UTC, kaisermann approved these changes

2020-03-26 17:47 UTC, guerreirobeatriz approved these changes

2020-03-30 15:22 UTC, merged

2020-03-30 15:34 UTC, klzns commented
@allcontributors add @lucasayb for code